import { readdirSync, statSync, writeFileSync } from "fs";
import { join, relative, sep } from "path";
import { fileURLToPath } from "url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const SRC_DIR = join(__dirname, "../packages/core/src");
const INDEX_FILE = join(SRC_DIR, "index.ts");

function getFiles(dir: string): string[] {
  const entries = readdirSync(dir);
  return entries.flatMap((entry) => {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) return getFiles(fullPath);
    if (!entry.endsWith(".ts")) return [];
    if (fullPath === INDEX_FILE) return [];
    return [fullPath];
  });
}

const files = getFiles(SRC_DIR);

const exportList = files
  .map((file) => {
    const rel = relative(SRC_DIR, file)
      .split(sep)
      .join("/")
      .replace(/\.ts$/, ".js");
    return `export * from "./${rel}";`;
  })
  .join("\n");

const content = `#!/usr/bin/env node\n// Auto-generated by generate-barrel.ts — do not edit manually\n${exportList}\n`;

writeFileSync(INDEX_FILE, content, "utf-8");
console.log(`✅ Barrel written with ${files.length} file(s) to index.ts`);
